### ISSUE TITLE
Todo-List Project

### ISSUE THREAD

**Issue by TImA97** [eort/rlddm#2]
- [x] Get a fundamental understanding of models and bayesian modeling
- [ ] play around with example data used in paper for HDDM
- [ ] check out rlssm by Fontanesi
- [ ] Get acquainted with RL-models in Python
- [ ] Get acquainted with DDMs in Python
- [ ] Understand structure of data to be analyzed
